site_name: Yacht Documentation
theme:
  name: material
  icon:
    repo: fontawesome/brands/git-alt
  favicon: assets/images/favicon.ico
  logo: assets/images/logo.svg
  custom_dir: overrides
extra_css:
  - stylesheets/extra.css
nav:
  - Home: index.md
  - Installation:
    - 'Requirements' : 'Installation/requirements.md'
    - 'Install Yacht' : 'Installation/yacht.md'
    - 'Getting Started' : 'Installation/gettingstarted.md'
    - 'ARM' : 'Installation/arm.md'
    - 'MacOS' : 'Installation/macos.md'
  - Templates:
    - 'Templates Explained' : 'Templates/templates.md'
    - 'Template Variables' : 'Templates/variables.md'
  - Pages:
    - 'Dashboard' : 'Pages/dashboard.md'
    - 'Applications' : 'Pages/applications.md'
    - 'Templates' : 'Pages/templates.md'
    - Resources:
      - 'Networks' : 'Pages/networks.md'
      - 'Volumes' : 'Pages/volumes.md'
      - 'Images' : 'Pages/images.md'
    - 'Server Settings' : 'Pages/serverSettings.md'
    - 'User Settings' : 'Pages/userSettings.md'
  - Projects (compose):
    - 'Projects Explained' : 'Projects/explained.md'
    - 'Advanced Projects' : 'Projects/advanced.md'
  - Advanced:
    - 'Reverse Proxy' : 'Advanced/proxy.md'
    - 'ARM (RPI)' : 'Advanced/arm.md'
  - Developer Info:
    - 'Developer Setup' : 'Developer_Information/DeveloperSetup.md'

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - pymdownx.tabbed
  - admonition
  - pymdownx.details

plugins:
  - search
  - git-revision-date-localized:
      type: timeago

google_analytics:
  - UA-179798260-1
  - auto

repo_url: https://github.com/SelfhostedPro/Yacht
repo_name: SelfhostedPro/Yacht
edit_uri: "https://github.com/SelfhostedPro/Yacht-Docs/edit/master/docs"